### ISSUE TITLE
PCA

### ISSUE THREAD

**Issue by CourtneyCrossfire** [tkimhofer/pym8#2]
Hi Torben, 

Please note the following- 

1) When you pre-define the chemical shift the visualizations appear like this- 
![image](https://user-images.githubusercontent.com/56920678/139631887-14b94109-0052-41c3-b49a-509c3dabab34.png)
I am unsure if you would like them to appear across the full image length. 

2) PCA scores plot does not have the option to label data points/customise colour groups. 

Many thanks,
C

**Comment by tkimhofer** [comment]
Cheers Courtney!

In the updated version issue 1 is resolved - and you can include pca scores labels with argument lab of pca function (see also updated function documentation). Manual scores colour selection is a great idea but low priority at the moment, but will keep you updated!
