### ISSUE TITLE
ispec

### ISSUE THREAD

**Issue by CourtneyCrossfire** [tkimhofer/pym8#3]
Hi T,

The random lines remain an issue even with no pre-processing
![Screenshot 2021-11-02 at 15 35 06](https://user-images.githubusercontent.com/56920678/139804678-d39f504e-4630-4d38-830a-6ccd5170905d.png)
: 

Hope that helps

**Comment by tkimhofer** [comment]
Can you send me your data that I can reproduce this?

**Comment by CourtneyCrossfire** [comment]
its the Std&Sup pickle on Kyles USB :)
