### ISSUE TITLE
preproc.calibrate_doubl

### ISSUE THREAD

**Issue by CourtneyCrossfire** [tkimhofer/pym8#5]
Hi T,

I only got this function to work after- 

1. [0] removed from get_idx
2. mm8.utility added to baseline 
3. mm8.utility added to "tf.cast(doub...) 

Works fine now I believe. 

Also can't get Marias PCA's to run on her computer (they run on mine)
- error is with sklearn/validation
- "ValueError: input contains NaN, infinity or a value too large for dtype('float64')

**Comment by tkimhofer** [comment]
Merci and code is updated!
